version: 0.2

phases:
  pre_build:
    commands:
      - echo Login to Docker Hub...
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $DOCKER_IMAGE .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Push built image to Docker Hub...
      - docker push $DOCKER_IMAGE
